### PR TITLE
Refactor and tests

### PR DESCRIPTION
**Pull request by andreineculau**
alternative to #2

### CODE REVIEW

**Comment by andreineculau** [comment]
@IanSavchenko the pull request branch had a "fixup" commit, I was going to rebase after you a would approve the review -- it still looks pending (yellow circle)

I'll push force to master now

Reference: http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html

**Comment by IanSavchenko** [comment]
@andreineculau Sorry, didn't see that. Strange that my circle is still yellow

**Review by IanSavchenko — COMMENTED** [review]
All good

**Comment by IanSavchenko** [comment]
Ok, got it now.

**Pull request merged**
